name: Lint XML
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt update -q && apt install -qy libxml2-utils
    - name: Run xmllint
      env:
        git_sha: ${{ github.sha }}
      run: |
        for file in $(git diff-tree --no-commit-id --name-only -r ${git_sha}); do
          if [[ ${file} == *.xml ]]; then
            xmllint "${file}"
          fi
        done;
